### ISSUE TITLE
The configuration parameter in Kernel_Layer.Network_stack.TCP_Syncookies is incorrect

### ISSUE THREAD

**Issue by safiyat** [trimstray/the-practical-linux-hardening-guide#11]
The configuration parameter in Kernel_Layer.Network_stack.TCP_Syncookies is incorrect.

On the page https://github.com/trimstray/the-practical-linux-hardening-guide/wiki/Network-stack#tcp-syncookies, the configuration parameter is that of source-packet-routing and not tcp_syncookies, as mentioned in the OpenSCAP document.

Link: https://static.open-scap.org/ssg-guides/ssg-rhel7-guide-C2S.html#xccdf_org.ssgproject.content_rule_sysctl_net_ipv4_tcp_syncookies

**Comment by trimstray** [comment]
Fixed. My mistake - you're right! Thanks!
