### ISSUE TITLE
improvement ideas for dev-sec project?

### ISSUE THREAD

**Issue by artem-sidorenko** [trimstray/the-practical-linux-hardening-guide#3]
Hey,

Thanks for a good summary!

I'm core maintainer of dev-sec project, not sure if you already know this project. We provide hardening automation packages for ansible/puppet/chef including automated tests for inspec.

We covered almost all of the things in your guide, which can be automated(e.g. setting of grub password or enforcing the permissions of the common directories). Not sure if we missed something or if you have any other ideas. We would be happy to know them :)

Maybe its a good idea to provide somewhere a reference to dev-sec in your guide, so people can easily find the project if they are looking for some automated solutions around.

https://dev-sec.io
https://github.com/dev-sec/

Thank you!
Artem

**Comment by trimstray** [comment]
Dear @artem-sidorenko!

Yes, I know these projects. It's great idea to add information about them to each chapter.

**Comment by micheldefforge** [comment]
Le Guide de Linux à continuer sur des roulettes. By.
